config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  # resources :tweets, only: [:new, :create, :index]
  resources :tweets, only: [:index]
  get '/tweets/search', to: 'tweets#search'
  get '/tweets/search_results', to: 'tweets#results'
  get '/tweets/start', to: 'tweets#start'
  root to: 'tweets#home'
end

app/models/tweet.rb
require 'redis'
require 'json'

class Tweet

  def self.get_user(user)

    Twitter::Streaming::Client.new do |config|
      config.consumer_key        = Rails.application.config.twitter_key
      config.consumer_secret     = Rails.application.config.twitter_secret
      config.access_token        = user.oauth_token
      config.access_token_secret = user.oauth_secret
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    # puts where(auth.slice(:provider, :uid))
    # binding.pry
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider     = auth.provider
      user.uid          = auth.uid
      user.name         = auth.info.name
      user.oauth_token  = auth.credentials.token
      user.oauth_secret = auth.credentials.secret
      user.save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to tweets_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
require 'streamer/sse'

class TweetsController < ApplicationController
  include ActionController::Live

  def index
  end

  def start
    response.headers['Content-Type'] = 'text/javascript'
    client = Tweet.get_user(current_user)
    client.sample do |tweet|
      if tweet.is_a?(Twitter::Tweet) && !tweet.geo.nil?
        p 'fetching tweets'
        p tweet.geo["coordinates"]
        $redis.publish('tweets.create', tweet.geo["coordinates"].to_json)
      end

    end

    render nothing: true
  end

  def home
    render layout: 'application', text: ''
  end

  def results
    # @twitter_user = Tweet.get_user(current_user)
    response.headers['Content-Type'] = 'text/event-stream'
      sse = Streamer::SSE.new(response.stream)
      redis = Redis.new
      redis.subscribe('tweets.create') do |on|
        on.message do |event, data|
          sse.write(data, event: 'tweets.create')
        end
      end
      render nothing: true
    rescue IOError
      # Client disconnected
    ensure
      redis.quit
      sse.close
    # end
  end
  # private
  # def twitter_params
  #   params.require(:tweet).permit(:message)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/show.html.erb
<h1>Home#show</h1>
<% if !current_user.nil? %>
    <p>Click The link below to send a tweet.</p>
    <%= link_to "Send a Tweet", new_tweet_path %>
    <%= link_to "Get user Tweet", tweets_search_path %>
<% else %>
    <p>You must log in to send a tweet.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter Pulse</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>
  </head>
  <body>
      <% if current_user %>
        <div class="top">Welcome to twtPulse</div> <div class="top"><strong><%= current_user.name %></strong>! <%= link_to "Sign out", signout_path %></div>


      </div>
      <% else %>
      <div id="landing-container">
        <div class="landing">
          <%= link_to "","/auth/twitter", id: "sign_in", class: "twitter-bird step" %>
        </div>
        <div class="site-title">
          <h1>twtPulse</h1>
        </div>
        <div class="bubble"></div>
      </div>
      <% end %>
    <div>
      <%= yield %>
      <% if current_user %>
        <script src="http://d3js.org/d3.v3.min.js"></script>
        <script src="http://d3js.org/topojson.v0.min.js"></script>
        <script>
          var width = 1200,
              height = 1000;

          var projection = d3.geo.mercator()
              .center([0, 0 ])
              .scale(200)
              // .rotate([-180,0])
              .translate([width / 2, height / 2]);

          var svg = d3.select("body").append("svg")
              .attr("width", width)
              .attr("height", height);

          var path = d3.geo.path()
              .projection(projection);

          var g = svg.append("g")

          d3.json("/assets/topo.json",
            function(error, topology) {

              g.selectAll("path")
               .data(topojson.object(topology, topology.objects.countries).geometries)
               .enter()
               .append("path")
               .attr("d", path)
          });

            // zoom and pan
            // var zoom = d3.behavior.zoom()
            //     .on("zoom",function() {
            //         g.attr("transform","translate("+
            //             d3.event.translate.join(",")+")scale("+d3.event.scale+")");
            //         g.selectAll("circle")
            //             .attr("d", path.projection(projection));
            //         g.selectAll("path")
            //             .attr("d", path.projection(projection));
            //
            //     });

            // svg.call(zoom)

        </script>
      <% end %>
    </div>
    <button class="button"></button>
  </body>
</html>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<h1>Success!</h1>
<p>Your tweet has been sent!</p>
<%= link_to "Would you like to send another?", new_tweet_path %>

app/views/tweets/index.html.erb
<!-- <span><%#= link_to "Start Stream", tweets_search_results_path %></span> -->

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>
  <%= form_for :tweet, url: tweets_path, method: :post do |f| %>
    <%= f.text_field :message %>
    <%= f.submit "Get Tweets" %>
  <% end %>
</p>

app/views/tweets/results.html.erb
<% @twitter_user.each do |tweet|%>
  <p><%= tweet["text"] %></p>
  <p><%= tweet["place"]["full_name"] %></p>
  <p><%= tweet["geo"]["coordinates"] %></p>
  <hr>
<% end %>

<hr>
<% @twitter_user.each.with_index do |coor, i| %>
  <% if i != (@twitter_user.size - 1)  %>
    <p><%= coor["geo"]["coordinates"].reverse %>,</p>
  <% else %>
    <p><%= coor["geo"]["coordinates"].reverse %></p>
  <% end %>
<% end %>
<hr>
<% @twitter_user.each.with_index do |coor, i| %>
  <% if i != (@twitter_user.size - 1)  %>
    <p><%= coor["geo"]["coordinates"][1] %>,
       <%= coor["geo"]["coordinates"][0] %>
    </p>
  <% else %>
    <p><%= coor["geo"]["coordinates"][1] %>,
       <%= coor["geo"]["coordinates"][0] %>
    </p>
  <% end %>
<% end %>